Feature 1
Abenezer-Tilahun/Bookstore pull request #1
Opened 2022-03-31 15:00 UTC by Abenezer-Tilahun

2022-03-31 19:59 UTC, GzimAsani requested changes
# Hi  @Abenezer-Tilahun                 
Good job so far! You are almost done :+1:  :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight:
- Good job with the git-flow :+1:
- Good PR description :clap: 

## Required Changes ♻️ 
- [x] _Check the comments below :arrow_double_down: _

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-31 19:59 UTC, GzimAsani commented on src/component/BookList.js
> +  }
- [x] This is throwing an error
![Screenshot from 2022-03-31 21-52-00](https://user-images.githubusercontent.com/62705947/161137809-b2452f76-ad42-473b-87ec-4926c64dfe94.png)

- [x] You should create a `book`  component and render them in this component
- [x] You should also render here the `AddBookForm` component

2022-03-31 19:59 UTC, GzimAsani commented on src/component/BookList.js
> +      There is no books to show.
- [x] Remember when creating the book component:
- That it should take  the data as a prop and render the title and author
- Should have a button for removing the books(It is not necessary to work though)

2022-03-31 19:59 UTC, GzimAsani commented on src/component/AddBookForm.js
> +}
- [x] This form should have two inputs for `title` and `author` of the book

2022-03-31 19:59 UTC, GzimAsani commented on src/component/Header.js
> +function Header() {
- [x] You should have a `Categories` component which should display only a button with text "Check status"

2022-04-01 04:46 UTC, arslanbisharat commented
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-04-01 05:22 UTC, merged

2022-04-09 20:33 UTC, Abenezer-Tilahun commented on src/component/BookList.js
> +  }
I will do that . Thanks for suggestion.

2022-04-09 20:33 UTC, Abenezer-Tilahun commented on src/component/BookList.js
> +      There is no books to show.
Done.

2022-04-09 20:34 UTC, Abenezer-Tilahun commented on src/component/AddBookForm.js
> +}
Ok i will add input for title and author for book.

2022-04-09 20:35 UTC, Abenezer-Tilahun commented on src/component/Header.js
> +function Header() {
I already include Categories component which should display only a button with text "Check status"